# Generated by Django 5.2.1 on 2025-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('prioridad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Tareas',
            },
        ),
    ]
